header_text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

HO = "A harmonic oscillator potential is an idealized spring - the further you go from equilibrium, the stronger the restoring force is. This is represented in Hook's law, F=kx, where F is the force, k is the spring constant and x is the displacement from equilibrium. For our potential we are concerned with the potential energy, V = 1/2*k*x^2. For a quantum system the energy levels are proportional to n+1/2 where n is an integer value starting at 0. Harmonic oscilators are good for small displacements or small values of n. However, as you move further from equilibrium anharmonic components start to dominate."

Morse = "A Morse potential is a simple improvement on the harmonic oscillator. It is of the form V=De*(1-e^(-a*x))^2, where x (again) is the displacement from equlibrium, De is the 'well depth', and a controls the width of the well. As a model for a diatomic molecule, De can be thought of as the dissaciataion energy. The energy levels are quantized, with integer values starting from 0. However there is an upper bound to these numbers, representing a dissacosciated molecule."

Box = 'Explanation of Step Potential goes here'

Bar = 'Explanation of a barrier goes here'

Open = 'A particle in a box is a standard starting point for studys of Quantum Mechanics. In a quantum system, a particle in a box can only have certain well defined energies, which limit the likelihood of the particle be measured at a given postion at any time. These probabilities take the form of a square of a sine function, with the requirement that the probability must be equal to 0 at either end of the box - that is, the particle can not exit the box. This second requirement means that the sine function must be of the form sin(nx), where n is a whole number. Although a simple model, it can be used to describe some real world situations, like a conjugated polyene in chemistry. A conjugated polyene is a long straight molecule whose structure allows electrons to traverse its length'